### ISSUE TITLE
Time shift issue.

### ISSUE THREAD

**Issue by kenti714** [elehobica/pico_ntp2jjy#1]
Hello,

I tried your pico_jjy_tx scripcts on Raspbery pico w.
The time seems to shift by 1 to 2 seconds.

I tried ntp server is below.

ntptime.host = "ntp.nict.jp"
https://www.nict.go.jp/JST/JST5.html

How about Solution or Idea?

Thanks & Regards.
kenti714

**Comment by elehobica** [comment]
Hi @kenti714 
Thanks for reporting the issue.

I have checked again, indeed it looks 1 second earlier than the time of NICT site displays.

Could I ask several confirmations?
* In your environment, as I observed, the clock adjusted by this JJY transmitter is earlier than NICT clock? (in precise, _earlier_ means for example that clock indicates 9:00:01 when NICT clock indicates 9:00:00)
* For the part you described as 1 to 2 sec, does that mean it differs sometimes 1 sec and sometimes 2 sec? or it differs always certain amount of time between 1 and 2 sec?

For the (temporary) workaround of time shift value, you can revise line 236:

`t = self.lcTime.now(1)  # time for next second`

If you would like to give 1 second delay, put `now(0)` instead of `now(1)`. I've never tried the negative number for this, but it should work as well if you want to try more than 2 seconds delay.

Anyway, I've adjusted seconds unit synchronization experimentally by the clock that I have. Therefore, the individual clock dependency could not be eliminated. The test report of other clocks as you did is very appreciated.

**Comment by kenti714** [comment]
Hi @elehobica 
Thank you for reply.

> In your environment, as I observed, the clock adjusted by this JJY transmitter is earlier than NICT clock? (in precise, earlier means for example that clock indicates 9:00:01 when NICT clock indicates 9:00:00)
> For the part you described as 1 to 2 sec, does that mean it differs sometimes 1 sec and sometimes 2 sec? or it differs always certain amount of time between 1 and 2 sec?

Yes, That's true.
I Tried adjust by your JJY transmitter script was earlier than NICT clock for 1 to 2 sec.

> If you would like to give 1 second delay, put now(0) instead of now(1). I've never tried the negative number for this, but it should work as well if you want to try more than 2 seconds delay.

Thank you for the solution!
I'm going to change the script to that now and check it out.

FYI, I'm use a circuit like this to set the clocks in my house.
![image](https://github.com/elehobica/pico_jjy_tx/assets/65384127/92eed270-c422-40f8-9dcb-08262a58585b)

The signal can reach from the corner of the desk to the opposite side! :)

Thanks&Regards.
kenti714

**Comment by elehobica** [comment]
@kenti714 Thank you for the report.
okay, if `t = self.lcTime.now(0)` works for correct synchronization for seconds unit, I will revise the repository, too.

Also thanks for the circuit diagram you're using. it looks interesting to use audio amplifier, which will work for suppressed gain.
As for the input signal of the amplifier, I'm not for sure about 'T' input of PAMP8403, however, the output from Pico W (GP2, GP3) is differential. Therefore, if single-ended signal is suitable, then I'd rather recommend to use GP2 and GND (or GP3 and GND).

**Comment by kenti714** [comment]
Hi @elehobica 

> the output from Pico W (GP2, GP3) is differential.  

oops...!
I writedown diagram was incorrect.
The correct figure is GP2 and GND.

Thanks :)

kenti714

**Comment by kenti714** [comment]
Hi @elehobica 

I have tried it and report below that it has worked fine until now. :)

- Fix of line 236 to `t = self.lcTime.now(-1)`
 Not earlier than NICT time. However, lags behind NICT time by 1 second or less. (about 500 milliseconds.)
I think this is good enough for practical use.
Depending on another environment, you may need to fix this part. :)

- `PAMP8403` is typo... `PAM8403` is true.
- 'T' input for PAM8403 is GND.
 The signals output by GP2 and GP3 are originally received by earphones. Instead, they are put into the input of PAM8403, so it is correct to use GP2 and GP3.

I have been running it for more than 24 hours now and it is works fine.

Thanks&Regards.

kenti714

**Comment by elehobica** [comment]
Thank you for the report.

I understood that in your case, `self.lcTime.now(-1)` can adjust to minimizing seconds unit delay. On the other hand, I'd like to exclude the dependency of individual clock device factors. Therefore, I will do more investigation from specification's point of view to finalize the value to shift. For the moment, I'm not aggressive to put negative delay on it (except for the workaround purpose as you did).

For the output signal, to avoid misunderstanding, I added the comment about single-ended usage on Readme.md. I'm afraid that IO buffer of GP3 could be broken if it is connected to GND.

**Comment by kenti714** [comment]
Hi @elehobica 

Thank you for reply.

Okay.
I finally composed it with your suggestions.
It worked fine.　:)
![jjy_kenti714](https://github.com/elehobica/pico_jjy_tx/assets/65384127/58f9c920-7956-4bf5-971e-02c78656b980)

RP Pico w GP2 and GND is PAM8403 R and GND connected.

Thank you for your support.

kenti714

**Comment by elehobica** [comment]
Already the issue has been closed, however I would like to leave my comment to you and those who are facing the similar issue.

From the conclusion to say, I finally choose `self.lcTime.now(0)`.
According to [JJY specification](https://jjy.nict.go.jp/jjy/trans/index.html), Marker M needs to be synchronized with the starting edge of 0 second of every minute. Therefore, this is the way to adjust the transmitting signal timing which is free from individual clock device factor.

The method to confirm if the signal is synchronized is easy. At [line 40](https://github.com/elehobica/pico_jjy_tx/blob/main/pico_jjy_tx.py#L40), set audible frequency such as 1000 ~ 10000 as temporary. Marker M is located at the 2nd point of where short signal (0.2sec) repeats twice.
Through the confirmation above, I have concluded to set `self.lcTime.now(0)` as minimum delay point from JJY _transmitting_ signal's point of view.

Thus, if the clock device side still shows the seconds unit delay, for the moment, I need to say, it seems that the delay is caused by the clock device, not the emulated JJY signal. Therefore, it's out of scope of this repository to meet such individual clock situations, however of course setting the arbitrary delay value on `self.lcTime.now(n)` can still work for the workaround of particular situations.

I hope this information helps for some situations to be understood.
Thanks to @kenti714 for addressing this issue.
